spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: trimhelp-ui
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.206.128:8848
  thymeleaf:
    cache: false
    prefix: classpath:/templates/  #prefix：指定模板所在的目录
    suffix:  .html
    mode: LEGACYHTML5

server:
  port: 10201

dubbo:
  application:
    name: trimhelp-ui
    qos-enable: false
  registry:
    address: nacos://192.168.206.128:8848
  scan:
    basePackages: com.youfull.hrimhelp.ui.service

management:
  endpoints:
    web:
      exposure:
        include: "*"




